/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type NewLinkRequest struct {
	Url string `json:"url"`

	Beauty string `json:"beauty,omitempty"`
}
