name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
     - name: "Run deploy on server"
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }} 
          key: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/URLShort
            git pull
            docker stop $(docker ps -q --filter ancestor=docker-shortener-v1)
            docker build --tag docker-shortener-v1 .
            docker run -d --publish 80:8080 docker-shortener-v1
